### ISSUE TITLE
Alphametic: SyntaxError: too many statically nested blocks

### ISSUE THREAD

**Issue by rickrich** [enigmatic-code/py-enigma#1]
`python -m /home/rick/proj/py-enigma/enigma Alphametic 'A  -  B  -  C  -  D  -  E  -  F  +  G  +  H  +  I  -  J  -  K  +  L  -  M  +  N  -  O  +  P  +  Q  +  R  +  S  -  T  -  U  -  V  -  W  -  X  -  Y  +  Z  +  61  =  0' 'A  -  B  -  C  -  D  +  E  -  F  +  G  -  H  +  I  -  J  -  K  -  L  -  M  +  N  -  O  +  P  -  Q  +  R  -  S  -  T  -  U  +  V  +  W  +  X  -  Y  +  Z  +  31  =  0' 'A  +  B  +  C  -  D  +  E  -  F  +  G  -  H  +  I  +  J  -  K  +  L  +  M  -  N  -  O  +  P  -  Q  -  R  +  S  -  T  +  U  -  V  -  W  +  X  -  Y  -  Z  +  21  =  0' 'A  +  B  -  C  -  D  -  E  +  F  +  G  -  H  +  I  +  J  +  K  +  L  +  M  +  N  -  O  -  P  +  Q  +  R  -  S  -  T  -  U  -  V  +  W  -  X  -  Y  +  Z  +  5  =  0' 'A  +  B  -  C  +  D  -  E  +  F  +  G  +  H  -  I  +  J  +  K  +  L  -  M  +  N  +  O  -  P  +  Q  -  R  -  S  -  T  -  U  -  V  -  W  -  X  -  Y  +  Z  +  71  =  0' 'A  -  B  -  C  +  D  -  E  -  F  +  G  -  H  +  I  -  J  -  K  +  L  -  M  +  N  +  O  +  P  -  Q  +  R  -  S  -  T  -  U  +  V  +  W  -  X  -  Y  +  Z  =  1' 'A  -  B  -  C  -  D  -  E  +  F  +  G  -  H  +  I  -  J  -  K  +  L  +  M  -  N  +  O  -  P  +  Q  +  R  -  S  +  T  +  U  +  V  -  W  -  X  +  Y  +  Z  =  91' 'A  -  B  +  C  +  D  -  E  +  F  +  G  +  H  +  I  -  J  +  K  -  L  +  M  -  N  -  O  -  P  -  Q  +  R  +  S  -  T  -  U  +  V  +  W  +  X  -  Y  -  Z  =  13' 'A  +  B  +  C  -  D  +  E  +  F  -  G  -  H  -  I  +  J  -  K  +  L  -  M  +  N  -  O  +  P  -  Q  +  R  +  S  -  T  -  U  +  V  +  W  -  X  -  Y  -  Z  +  57  =  0' 'A  -  B  -  C  +  D  -  E  -  F  -  G  +  H  +  I  +  J  +  K  +  L  +  M  +  N  -  O  +  P  -  Q  +  R  +  S  +  T  -  U  +  V  +  W  +  X  -  Y  -  Z  =  73' 'A  -  B  +  C  +  D  -  E  -  F  -  G  -  H  -  I  -  J  -  K  -  L  +  M  -  N  +  O  +  P  -  Q  +  R  -  S  -  T  +  U  +  V  +  W  +  X  +  Y  -  Z  =  29' 'A  +  B  -  C  -  D  -  E  -  F  +  G  +  H  +  I  -  J  +  K  -  L  +  M  +  N  +  O  +  P  +  Q  -  R  -  S  -  T  +  U  -  V  -  W  -  X  -  Y  +  Z  + 11  =  0' 'A  +  B  -  C  +  D  +  E  -  F  +  G  +  H  -  I  -  J  +  K  +  L  +  M  +  N  -  O  -  P  -  Q  +  R  -  S  +  T  -  U  +  V  -  W  +  X  -  Y  -  Z  +  11  =  0' 'A  +  B  -  C  -  D  -  E  +  F  -  G  +  H  -  I  -  J  -  K  -  L  -  M  +  N  -  O  +  P  +  Q  +  R  +  S  +  T  +  U  -  V  -  W  +  X  -  Y  +  Z  =  43' 'A  -  B  +  C  +  D  +  E  +  F  +  G  +  H  -  I  -  J  +  K  -  L  +  M  -  N  -  O  +  P  +  Q  -  R  +  S  -  T  -  U  +  V  +  W  +  X  -  Y  +  Z  =  13' 'A  -  B  +  C  -  D  -  E  -  F  -  G  -  H  -  I  +  J  +  K  -  L  +  M  -  N  -  O  -  P  +  Q  +  R  +  S  -  T  +  U  +  V  -  W  +  X  -  Y  -  Z  +  57  =  0' 'A  +  B  -  C  -  D  -  E  -  F  -  G  +  H  -  I  -  J  -  K  -  L  -  M  +  N  -  O  -  P  +  Q  +  R  -  S  -  T  -  U  -  V  -  W  +  X  -  Y  +  Z  +  135  =  0' 'A  +  B  -  C  +  D  +  E  -  F  -  G  -  H  -  I  +  J  +  K  -  L  +  M  +  N  -  O  -  P  +  Q  +  R  -  S  -  T  +  U  +  V  -  W  +  X  +  Y  +  Z  =  51' 'A  -  B  +  C  -  D  -  E  -  F  -  G  +  H  -  I  +  J  -  K  +  L  -  M  -  N  +  O  +  P  +  Q  -  R  -  S  +  T  +  U  -  V  -  W  +  X  +  Y  +  Z  =  9' 'A  -  B  -  C  -  D  -  E  -  F  -  G  +  H  -  I  -  J  +  K  -  L  -  M  -  N  +  O  -  P  +  Q  -  R  -  S  +  T  -  U  +  V  -  W  +  X  +  Y  +  Z  +  91  =  0' 'A  +  B  +  C  +  D  +  E  -  F  -  G  -  H  +  I  +  J  -  K  -  L  -  M  -  N  -  O  -  P  +  Q  +  R  -  S  -  T  +  U  +  V  -  W  -  X  +  Y  -  Z  +  47  =  0' 'A  -  B  +  C  -  D  -  E  -  F  -  G  -  H  -  I  +  J  -  K  -  L  -  M  -  N  -  O  -  P  +  Q  -  R  +  S  -  T  -  U  -  V  -  W  -  X  +  Y  -  Z  +  213  =  0' 'A  -  B  +  C  +  D  +  E  +  F  -  G  -  H  -  I  -  J  +  K  -  L  +  M  +  N  -  O  +  P  +  Q  -  R  -  S  +  T  -  U  +  V  -  W  -  X  -  Y  -  Z  +  59  =  0' 'A  +  B  +  C  -  D  +  E  +  F  -  G  -  H  -  I  -  J  -  K  -  L  -  M  -  N  -  O  -  P  +  Q  +  R  +  S  +  T  +  U  +  V  +  W  -  X  -  Y  +  Z  =  19' 'A  -  B  +  C  +  D  +  E  +  F  -  G  -  H  +  I  -  J  +  K  -  L  +  M  -  N  -  O  +  P  +  Q  -  R  +  S  +  T  +  U  +  V  +  W  -  X  +  Y  -  Z  =  83' 'A  -  B  -  C  +  D  -  E  +  F  -  G  +  H  -  I  +  J  +  K  -  L  -  M  +  N  -  O  -  P  -  Q  -  R  +  S  -  T  +  U  -  V  +  W  +  X  -  Y  +  Z  +  15  =  0'
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/rick/proj/py-enigma/enigma.py", line 8084, in <module>
    run(*args)
  File "/home/rick/proj/py-enigma/enigma.py", line 7843, in run
    _run_exit = (fn(list(args)) or 0)
  File "/home/rick/proj/py-enigma/enigma.py", line 5780, in command_line
    self.go()
  File "/home/rick/proj/py-enigma/enigma.py", line 5466, in go
    for s in self.solve(check=check, first=first, verbose=verbose):
  File "/home/rick/proj/py-enigma/enigma.py", line 5409, in solve
    if not self._prepared: self._prepare()
  File "/home/rick/proj/py-enigma/enigma.py", line 5390, in _prepare
    code = compile(prog, '<string>', 'exec')
SyntaxError: too many statically nested blocks
`

**Comment by enigmatic-code** [comment]
> On 23 Nov 2019, at 12:57 pm, rickrich <notifications@github.com> wrote:
> 
> python -m /home/rick/proj/py-enigma/enigma Alphametic 'A - B - C - D - E - F + G + H + I - J - K + L - M + N - O + P + Q + R + S - T - U - V - W - X - Y + Z + 61 = 0' 'A - B - C - D + E - F + G - H + I - J - K - L - M + N - O + P - Q + R - S - T - U + V + W + X - Y + Z + 31 = 0' 'A + B + C - D + E - F + G - H + I + J - K + L + M - N  - O + P - Q - R + S - T + U - V - W + X - Y - Z + 21 = 0' 'A + B - C - D - E + F + G - H + I + J + K + L + M + N - O - P + Q + R - S - T - U - V + W - X - Y + Z + 5 = 0' 'A + B - C + D - E + F + G + H - I + J + K + L - M + N + O - P + Q - R - S - T - U - V - W - X - Y + Z + 71 = 0' 'A - B - C + D - E - F + G - H + I - J - K + L - M + N + O + P - Q + R - S - T - U + V + W - X - Y + Z = 1' 'A - B - C - D - E + F + G - H + I - J - K + L + M - N + O - P + Q + R - S + T + U + V - W - X + Y + Z = 91' 'A - B + C + D - E + F + G + H + I - J + K - L + M - N - O - P - Q + R + S - T - U + V + W + X - Y - Z = 13' 'A + B + C - D + E + F - G - H - I + J - K + L - M + N - O  + P - Q + R + S - T - U + V + W - X - Y - Z + 57 = 0' 'A - B - C + D - E - F - G + H + I + J + K + L + M + N - O + P - Q + R + S + T - U + V + W + X - Y - Z = 73' 'A -  B + C + D - E - F - G - H - I - J - K - L + M - N + O + P - Q + R - S - T + U + V + W + X + Y - Z = 29' 'A + B - C - D - E - F + G + H + I - J + K - L + M + N + O + P + Q - R - S - T + U - V - W - X - Y + Z + 11 = 0' 'A + B - C + D + E - F + G + H - I - J + K + L + M + N - O - P - Q + R - S + T - U + V - W + X - Y - Z + 11 = 0' 'A +  B - C - D - E + F - G + H - I - J - K - L - M + N - O + P + Q + R + S + T + U - V - W + X - Y + Z = 43' 'A - B + C + D + E + F + G + H - I - J + K - L + M - N - O + P + Q - R + S - T - U + V + W + X - Y + Z = 13' 'A - B + C - D - E - F - G - H - I + J + K - L + M - N - O - P + Q + R + S - T + U + V - W + X - Y - Z + 57 = 0' 'A + B -  C - D - E - F - G + H - I - J - K - L - M + N - O - P + Q + R - S - T - U - V - W + X - Y + Z + 135 = 0' 'A + B - C + D + E - F - G - H - I + J + K - L + M + N - O - P  + Q + R - S - T + U + V - W + X + Y + Z = 51' 'A - B + C - D - E - F - G + H - I + J - K + L - M - N + O + P + Q - R - S + T + U - V - W + X + Y + Z = 9' 'A - B - C - D - E - F - G + H - I - J + K - L - M - N + O - P + Q - R - S + T - U + V - W + X + Y + Z + 91 = 0' 'A + B + C + D + E - F - G - H + I + J - K - L - M - N - O - P + Q + R - S - T + U + V - W - X + Y - Z + 47 = 0' 'A - B + C - D - E - F - G - H - I + J - K - L - M - N - O - P + Q - R + S - T - U - V - W - X + Y - Z + 213 = 0' 'A - B + C + D + E + F - G - H - I - J + K - L + M + N - O + P + Q - R - S + T - U + V - W - X - Y - Z + 59 = 0' 'A + B + C - D + E + F - G - H - I - J - K - L - M - N - O - P + Q + R + S + T + U + V + W - X - Y + Z = 19' 'A - B + C + D + E + F - G - H + I - J + K - L + M - N - O + P + Q - R + S + T + U + V + W - X + Y - Z = 83' 'A - B - C  + D - E + F - G + H - I + J + K - L - M + N - O - P - Q - R + S - T + U - V + W + X - Y + Z + 15 = 0' Traceback (most recent call last): File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/home/rick/proj/py-enigma/enigma.py", line 8084, in <module> run(*args) File "/home/rick/proj/py-enigma/enigma.py", line 7843, in run _run_exit = (fn(list(args)) or 0) File "/home/rick/proj/py-enigma/enigma.py", line 5780, in command_line self.go() File "/home/rick/proj/py-enigma/enigma.py", line 5466, in go for s in self.solve(check=check, first=first, verbose=verbose): File "/home/rick/proj/py-enigma/enigma.py", line 5409, in solve if not self._prepared: self._prepare() File "/home/rick/proj/py-enigma/enigma.py", line 5390, in _prepare code = compile(prog, '<string>', 'exec') SyntaxError: too many statically nested blocks

The [[ SubstitutedExpression() ]] solver uses the code fragments given to construct a program, which is then fed to the Python interpreter.

If you use too many symbols then the standard Python interpreter will throw:

  "SystemError: too many statically nested blocks"; or:
  "SyntaxError: too many statically nested blocks"

if the generated program has more than 20 levels of nested loops.

And it will also throw:

  "IndentationError: too many levels of indentation"

if there are more than 100 levels of indentation.

The easiest way to work around this is to use a Python interpreter that is not subject to these restrictions, such as the PyPy interpreter.

Although I can tell you that your collection of expressions is not going to have any solutions in base 10 as there are more than 10 symbols used, and in an alphametic problem symbols usually stand for different single digits.

In fact it looks like you have 26 linear expressions in 26 variables, so, even if you used the [[ --distinct="" ]] parameter to allow symbols to take on the same value the [[ SubstitutedExpression() ]] solver will have to try 10^26 possibilities for the symbol assignments, so it will take a long time.

But as it is a system of linear equations you can use the Gaussian elimination solver in the enigma.py to solve them (or any other solve for linear equations you have to hand), and find the values (if any) of the symbols (which will be rational, but not necessarily all integers in the range 0-9).

[code language="python"]
from enigma import matrix, printf

eqs = [
  ((+1, -1, -1, -1, -1, -1, +1, +1, +1, -1, -1, +1, -1, +1, -1, +1, +1, +1, +1, -1, -1, -1, -1, -1, -1, +1), -61),
  ((+1, -1, -1, -1, +1, -1, +1, -1, +1, -1, -1, -1, -1, +1, -1, +1, -1, +1, -1, -1, -1, +1, +1, +1, -1, +1), -31),
  ((+1, +1, +1, -1, +1, -1, +1, -1, +1, +1, -1, +1, +1, -1, -1, +1, -1, -1, +1, -1, +1, -1, -1, +1, -1, -1), -21),
  ((+1, +1, -1, -1, -1, +1, +1, -1, +1, +1, +1, +1, +1, +1, -1, -1, +1, +1, -1, -1, -1, -1, +1, -1, -1, +1), -5),
  ((+1, +1, -1, +1, -1, +1, +1, +1, -1, +1, +1, +1, -1, +1, +1, -1, +1, -1, -1, -1, -1, -1, -1, -1, -1, +1), -71),
  ((+1, -1, -1, +1, -1, -1, +1, -1, +1, -1, -1, +1, -1, +1, +1, +1, -1, +1, -1, -1, -1, +1, +1, -1, -1, +1), 1),
  ((+1, -1, -1, -1, -1, +1, +1, -1, +1, -1, -1, +1, +1, -1, +1, -1, +1, +1, -1, +1, +1, +1, -1, -1, +1, +1), 91),
  ((+1, -1, +1, +1, -1, +1, +1, +1, +1, -1, +1, -1, +1, -1, -1, -1, -1, +1, +1, -1, -1, +1, +1, +1, -1, -1), 13),
  ((+1, +1, +1, -1, +1, +1, -1, -1, -1, +1, -1, +1, -1, +1, -1, +1, -1, +1, +1, -1, -1, +1, +1, -1, -1, -1), -57),
  ((+1, -1, -1, +1, -1, -1, -1, +1, +1, +1, +1, +1, +1, +1, -1, +1, -1, +1, +1, +1, -1, +1, +1, +1, -1, -1), 73),
  ((+1, -1, +1, +1, -1, -1, -1, -1, -1, -1, -1, -1, +1, -1, +1, +1, -1, +1, -1, -1, +1, +1, +1, +1, +1, -1), 29),
  ((+1, +1, -1, -1, -1, -1, +1, +1, +1, -1, +1, -1, +1, +1, +1, +1, +1, -1, -1, -1, +1, -1, -1, -1, -1, +1), -11),
  ((+1, +1, -1, +1, +1, -1, +1, +1, -1, -1, +1, +1, +1, +1, -1, -1, -1, +1, -1, +1, -1, +1, -1, +1, -1, -1), -11),
  ((+1, +1, -1, -1, -1, +1, -1, +1, -1, -1, -1, -1, -1, +1, -1, +1, +1, +1, +1, +1, +1, -1, -1, +1, -1, +1), 43),
  ((+1, -1, +1, +1, +1, +1, +1, +1, -1, -1, +1, -1, +1, -1, -1, +1, +1, -1, +1, -1, -1, +1, +1, +1, -1, +1), 13),
  ((+1, -1, +1, -1, -1, -1, -1, -1, -1, +1, +1, -1, +1, -1, -1, -1, +1, +1, +1, -1, +1, +1, -1, +1, -1, -1), -57),
  ((+1, +1, -1, -1, -1, -1, -1, +1, -1, -1, -1, -1, -1, +1, -1, -1, +1, +1, -1, -1, -1, -1, -1, +1, -1, +1), -135),
  ((+1, +1, -1, +1, +1, -1, -1, -1, -1, +1, +1, -1, +1, +1, -1, -1, +1, +1, -1, -1, +1, +1, -1, +1, +1, +1), 51),
  ((+1, -1, +1, -1, -1, -1, -1, +1, -1, +1, -1, +1, -1, -1, +1, +1, +1, -1, -1, +1, +1, -1, -1, +1, +1, +1), 9),
  ((+1, -1, -1, -1, -1, -1, -1, +1, -1, -1, +1, -1, -1, -1, +1, -1, +1, -1, -1, +1, -1, +1, -1, +1, +1, +1), -91),
  ((+1, +1, +1, +1, +1, -1, -1, -1, +1, +1, -1, -1, -1, -1, -1, -1, +1, +1, -1, -1, +1, +1, -1, -1, +1, -1), -47),
  ((+1, -1, +1, -1, -1, -1, -1, -1, -1, +1, -1, -1, -1, -1, -1, -1, +1, -1, +1, -1, -1, -1, -1, -1, +1, -1), -213),
  ((+1, -1, +1, +1, +1, +1, -1, -1, -1, -1, +1, -1, +1, +1, -1, +1, +1, -1, -1, +1, -1, +1, -1, -1, -1, -1), -59),
  ((+1, +1, +1, -1, +1, +1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, +1, +1, +1, +1, +1, +1, +1, -1, -1, +1), 19),
  ((+1, -1, +1, +1, +1, +1, -1, -1, +1, -1, +1, -1, +1, -1, -1, +1, +1, -1, +1, +1, +1, +1, +1, -1, +1, -1), 83),
  ((+1, -1, -1, +1, -1, +1, -1, +1, -1, +1, +1, -1, -1, +1, -1, -1, -1, -1, +1, -1, +1, -1, +1, +1, -1, +1), -15),
]

(A, B) = zip(*eqs)
vs = matrix.linear(A, B)

for (s, v) in zip("ABCDEFGHIJKLMNOPQRSTUVWXYZ", vs):
  printf("{s} = {v}")
[/code]

[output]
A = 11
B = 3
C = 12
D = 16
E = 9
F = 13
G = 10
H = 1
I = 20
J = 5
K = 2
L = 6
M = 17
N = 22
O = 24
P = 7
Q = 8
R = 23
S = 18
T = 25
U = 26
V = 4
W = 14
X = 21
Y = 15
Z = 19
[/output]

The symbols do take on distinct integer values between 1 and 26.

So it would be theoretically possible to use the [[ SubstitutedExpression() ]] solve to find the values, if you specified it to use base 27 (each symbol represents a single digit in an alphametic problem), but as each of the 26 equations uses all of the symbols there are no short cuts and it would take ages to consider the 26^26 possible assignments.

Hope this helps.

Jim

-- 
Jim Randell
jim.randell@gmail.com
http://enigmaticcode.wordpress.com/

**Comment by rickrich** [comment]
I did it with http://www.bluebit.gr/matrix-calculator/linear_equations.aspx
Coefficients' matrix A:  and Right hand side matrix B:.  Both answers are right.
Thanks again.
